/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package mobi.bihu.crawler.sc.thrift;


import org.apache.thrift.TEnum;

public enum SelectType implements TEnum {
  MEMORYMORE(0),
  CPUMORE(1),
  DISKMORE(2),
  NETUSGMORE(3),
  AVERAGE(4),
  RANDOM(5);

  private final int value;

  private SelectType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SelectType findByValue(int value) { 
    switch (value) {
      case 0:
        return MEMORYMORE;
      case 1:
        return CPUMORE;
      case 2:
        return DISKMORE;
      case 3:
        return NETUSGMORE;
      case 4:
        return AVERAGE;
      case 5:
        return RANDOM;
      default:
        return null;
    }
  }
}
